# Generated by Django 5.2.6 on 2025-10-01 06:52

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=courses.models.handle_upload)),
                ('access', models.CharField(choices=[('any', 'Anyone'), ('email', 'Email Required')], default='any', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('soon', 'Coming Soon'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
