# Generated by Django 5.2.6 on 2025-10-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='can_preview',
            field=models.BooleanField(default=False, help_text='can user see this text?'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('soon', 'Coming Soon'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
