# Generated by Django 5.2.6 on 2025-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_timestamp_course_updated_lesson_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='link',
            new_name='notebook_link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='test_link',
            field=models.URLField(blank=True),
        ),
    ]
