# Generated by Django 5.2.6 on 2025-10-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_link_lesson_notebook_link_lesson_test_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='notebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='test_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
