# Generated by Django 5.2.6 on 2025-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lesson_notebook_link_alter_lesson_test_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='path',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
