# Generated by Django 5.2.6 on 2025-10-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='path',
        ),
    ]
