# Generated by Django 5.2.6 on 2025-11-16 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_remove_course_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название ноутбука"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "file",
                    models.FileField(
                        help_text="Загрузите .ipynb файл",
                        upload_to="notebooks/",
                        verbose_name="Jupyter Notebook файл (.ipynb)",
                    ),
                ),
                (
                    "github_repo",
                    models.CharField(
                        blank=True,
                        help_text="Например: username/repo-name (для Binder)",
                        max_length=200,
                        null=True,
                        verbose_name="GitHub репозиторий",
                    ),
                ),
                (
                    "github_branch",
                    models.CharField(
                        default="main",
                        help_text="Обычно main или master",
                        max_length=100,
                        verbose_name="Ветка GitHub",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Урок, к которому привязан ноутбук",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebooks",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jupyter Notebook",
                "verbose_name_plural": "Jupyter Notebooks",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
