# Generated by Django 5.2.6 on 2025-10-10 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
